DROP DATABASE IF EXISTS ABOGADOS
GO

CREATE DATABASE ABOGADOS
GO

ALTER AUTHORIZATION ON DATABASE :: ABOGADOS TO sa
GO

USE ABOGADOS
GO



CREATE TABLE ABOGADO 
    (
     Cod_Abog VARCHAR (20) NOT NULL , 
     No_Colegiado VARCHAR (20) NOT NULL , 
     DNI_NIE VARCHAR (20) NOT NULL, 
     Nomb_Abog VARCHAR (50) NOT NULL, 
     Apell_Abog VARCHAR (50) NOT NULL, 
     Cod_Judic VARCHAR (20) NOT NULL
		 --  ERROR: Datatype UNKNOWN is not allowed 
   )
GO

ALTER TABLE ABOGADO ADD CONSTRAINT ABOGADO_PK PRIMARY KEY CLUSTERED (Cod_Abog)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ACTUAC_ADM 
    (
     Cod_Recurso VARCHAR (20) NOT NULL , 
     Cod_Act_Adm VARCHAR (20) NOT NULL , 
     Tipo_Act_Adm VARCHAR (30) NOT NULL , 
     Fecha_Act_Adm DATE NOT NULL 
    )
GO

ALTER TABLE ACTUAC_ADM ADD CONSTRAINT ACTUAC_ADM_PK PRIMARY KEY CLUSTERED (Cod_Recurso)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE ACTUAC_ADM ADD CONSTRAINT ACTUAC_ADM_PKv1 UNIQUE NONCLUSTERED (Cod_Act_Adm)
GO

CREATE TABLE ACTUAC_JUDICIAL 
    (
     Cod_Judic VARCHAR (20) NOT NULL ,
--  ERROR: Datatype UNKNOWN is not allowed 
     Cod_Act_Jud VARCHAR (20) NOT NULL , 
     Tipo_Act_Jud VARCHAR (30) NOT NULL , 
     Fecha_Act_Jud DATE NOT NULL 
    )
GO

ALTER TABLE ACTUAC_JUDICIAL ADD CONSTRAINT ACTUAC_JUDICIAL_PK PRIMARY KEY CLUSTERED (Cod_Judic)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE ACTUAC_JUDICIAL ADD CONSTRAINT ACTUAC_JUDICIAL_PKv1 UNIQUE NONCLUSTERED (Cod_Act_Jud)
GO

CREATE TABLE ASESORIA 
    (
     Cod_Asesoria VARCHAR (20) NOT NULL , 
     Tipo_Asesoria VARCHAR (30) NOT NULL , 
     Fecha_Asesoria DATE NOT NULL , 
     Cod_Asesoria1 VARCHAR NOT NULL , 
     CLIENTE_Cod_Cliente VARCHAR (30) NOT NULL , 
     ABOGADO_Cod_Abog VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE ASESORIA ADD CONSTRAINT ASESORIA_PK PRIMARY KEY CLUSTERED (Cod_Asesoria)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CLIENTE 
    (
     Cod_Cliente VARCHAR (30) NOT NULL , 
     Telefono NUMERIC (9) NOT NULL , 
     Direccion VARCHAR (30) NOT NULL , 
     MES_HORAS DATE NOT NULL 
    )
GO

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY CLUSTERED (Cod_Cliente)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CLIENTE_FISICO 
    (
     Cod_Cliente VARCHAR (30) NOT NULL , 
     NIF_DNI_NIE VARCHAR (10) NOT NULL , 
     Nombre VARCHAR (50) NOT NULL , 
     Apellido VARCHAR (50) NOT NULL , 
     JUICIOS_Cod_Judic VARCHAR (20) NOT NULL ,
	 --  ERROR: Datatype UNKNOWN is not allowed 
    )
GO

ALTER TABLE CLIENTE_FISICO ADD CONSTRAINT CLIENTE_FISICO_PK PRIMARY KEY CLUSTERED (Cod_Cliente)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE CLIENTE_FISICO ADD CONSTRAINT CLIENTE_FISICO_PKv1 UNIQUE NONCLUSTERED (NIF_DNI_NIE)
GO

CREATE TABLE CLIENTE_JURIDICO 
    (
     Cod_Cliente VARCHAR (30) NOT NULL , 
     NIF_DNI_NIE VARCHAR (10) NOT NULL , 
     Nombre VARCHAR (50) NOT NULL , 
     Apellido VARCHAR (50) NOT NULL , 
     Nom_Rep VARCHAR (20) NOT NULL , 
     Apelli_Rep VARCHAR (50) NOT NULL , 
     NIE_Rep VARCHAR (20) NOT NULL , 
     DNI_NIE_Apod VARCHAR (30) , 
     Nomb_Apod VARCHAR (50) , 
     Cod_Judic VARCHAR (20) NOT NULL ,
--  ERROR: Datatype UNKNOWN is not allowed 
    )
GO

ALTER TABLE CLIENTE_JURIDICO ADD CONSTRAINT CLIENTE_JURIDICO_PK PRIMARY KEY CLUSTERED (Cod_Cliente)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE CLIENTE_JURIDICO ADD CONSTRAINT CLIENTE_JURIDICO_PKv1 UNIQUE NONCLUSTERED (NIF_DNI_NIE)
GO

CREATE TABLE CONTRATOS 
    (
     Cod_Doc VARCHAR (20) NOT NULL , 
     Tipo_Cont VARCHAR (30) NOT NULL , 
     Fecha_Cont DATE NOT NULL , 
     Fecha_Venc_Cont DATE NOT NULL , 
     CLIENTE_Cod_Cliente VARCHAR (30) NOT NULL , 
     ABOGADO_Cod_Abog VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE CONTRATOS ADD CONSTRAINT CONTRATOS_PK PRIMARY KEY CLUSTERED (Cod_Doc)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE DOC_MERCANTIL 
    (
     Cod_Mercantil VARCHAR (20) NOT NULL , 
     Fecha_Doc_Merc DATE NOT NULL , 
     Socios VARCHAR (50) , 
     Directores VARCHAR (50) , 
     Tesorero VARCHAR (50) , 
     Tipo_Doc_Merc VARCHAR (30) NOT NULL , 
     CLIENTE_Cod_Cliente VARCHAR (30) NOT NULL , 
     ABOGADO_Cod_Abog VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE DOC_MERCANTIL ADD CONSTRAINT DOC_MERCANTIL_PK PRIMARY KEY CLUSTERED (Cod_Mercantil)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE FACTURA 
    (
     No_Factura VARCHAR (20) NOT NULL , 
     Fecha_Fact DATE NOT NULL , 
     No_Horas NUMERIC (10) NOT NULL , 
     No_Horas_1 NUMERIC (10) NOT NULL , 
     Precio_Horas NUMERIC (10,2) NOT NULL , 
     Total_Fact NUMERIC (10,2) NOT NULL , 
     Pagada BIT 
    )
GO

ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_PK PRIMARY KEY CLUSTERED (No_Factura)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE HORAS_POR_FACTURAR 
    (
     MES_HORAS DATE NOT NULL , 
     Facturada BIT NOT NULL , 
     MES_HORAS1 DATE NOT NULL , 
     CLIENTE_Cod_Cliente VARCHAR (30) NOT NULL , 
     FACTURA_No_Factura VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE HORAS_POR_FACTURAR ADD CONSTRAINT HORAS_POR_FACTURAR_PK PRIMARY KEY CLUSTERED (MES_HORAS)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE JUICIOS 
    (
     Cod_Judic VARCHAR (20) NOT NULL ,
--  ERROR: Datatype UNKNOWN is not allowed 
     Tribunal VARCHAR (50) NOT NULL , 
     Juez VARCHAR (30) NOT NULL , 
     Fecha_Demanda DATE NOT NULL , 
     Cod_Judic1 VARCHAR (20) NOT NULL ,
	 --  ERROR: Datatype UNKNOWN is not allowed 
   --  ERROR: Datatype UNKNOWN is not allowed 
     ABOGADO_Cod_Abog VARCHAR (20) NOT NULL , 
     CLIENTE_Cod_Cliente VARCHAR (30) NOT NULL 
    )
GO

ALTER TABLE JUICIOS ADD CONSTRAINT JUICIOS_PK PRIMARY KEY CLUSTERED (Cod_Judic)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PODERES 
    (
     Cod_Poder VARCHAR (20) NOT NULL , 
     Tipo_Poder VARCHAR (50) NOT NULL , 
     Fecha_Poder DATE NOT NULL , 
     Fecha_Venc_Poder DATE , 
     NIF_DNI_NIE VARCHAR NOT NULL , 
     ABOGADO_Cod_Abog VARCHAR (20) NOT NULL ,
	 CLIENTE_Cod_Cliente VARCHAR (30) NOT NULL
    )
GO

ALTER TABLE PODERES ADD CONSTRAINT PODERES_PK PRIMARY KEY CLUSTERED (Cod_Poder)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE RECURSOS 
    (
     Cod_Recurso VARCHAR (20) NOT NULL , 
     Tipo_Recurso VARCHAR (50) NOT NULL , 
     Aut_Adm VARCHAR (50) NOT NULL , 
     Fecha_Recurso DATE NOT NULL , 
     Cod_Recurso1 VARCHAR NOT NULL , 
     Cod_Recurso2 VARCHAR NOT NULL , 
     CLIENTE_Cod_Cliente VARCHAR (30) NOT NULL , 
     ABOGADO_Cod_Abog VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE RECURSOS ADD CONSTRAINT RECURSOS_PK PRIMARY KEY CLUSTERED (Cod_Recurso)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE ACTUAC_ADM 
    ADD CONSTRAINT ACTUAC_ADM_RECURSOS_FK FOREIGN KEY 
    ( 
     Cod_Recurso
    ) 
    REFERENCES RECURSOS 
    ( 
     Cod_Recurso 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ACTUAC_JUDICIAL 
    ADD CONSTRAINT ACTUAC_JUDICIAL_JUICIOS_FK FOREIGN KEY 
    ( 
     Cod_Judic
    ) 
    REFERENCES JUICIOS 
    ( 
     Cod_Judic 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ACTUAC_JUDICIAL 
    ADD CONSTRAINT ACTUAC_JUDICIAL_JUICIOS_FKv2 FOREIGN KEY 
    ( 
     Cod_Judic
    ) 
    REFERENCES JUICIOS 
    ( 
     Cod_Judic 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ASESORIA 
    ADD CONSTRAINT ASESORIA_ABOGADO_FK FOREIGN KEY 
    ( 
     ABOGADO_Cod_Abog
    ) 
    REFERENCES ABOGADO 
    ( 
     Cod_Abog 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ASESORIA 
    ADD CONSTRAINT ASESORIA_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_Cod_Cliente
    ) 
    REFERENCES CLIENTE 
    ( 
     Cod_Cliente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CLIENTE_FISICO 
    ADD CONSTRAINT CLIENTE_FISICO_CLIENTE_FK FOREIGN KEY 
    ( 
     Cod_Cliente
    ) 
    REFERENCES CLIENTE 
    ( 
     Cod_Cliente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CLIENTE_FISICO 
    ADD CONSTRAINT CLIENTE_FISICO_JUICIOS_FK FOREIGN KEY 
    ( 
     JUICIOS_Cod_Judic
    ) 
    REFERENCES JUICIOS 
    ( 
     Cod_Judic 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CLIENTE_JURIDICO 
    ADD CONSTRAINT CLIENTE_JURIDICO_CLIENTE_FK FOREIGN KEY 
    ( 
     Cod_Cliente
    ) 
    REFERENCES CLIENTE 
    ( 
     Cod_Cliente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CONTRATOS 
    ADD CONSTRAINT CONTRATOS_ABOGADO_FK FOREIGN KEY 
    ( 
     ABOGADO_Cod_Abog
    ) 
    REFERENCES ABOGADO 
    ( 
     Cod_Abog 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CONTRATOS 
    ADD CONSTRAINT CONTRATOS_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_Cod_Cliente
    ) 
    REFERENCES CLIENTE 
    ( 
     Cod_Cliente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOC_MERCANTIL 
    ADD CONSTRAINT DOC_MERCANTIL_ABOGADO_FK FOREIGN KEY 
    ( 
     ABOGADO_Cod_Abog
    ) 
    REFERENCES ABOGADO 
    ( 
     Cod_Abog 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOC_MERCANTIL 
    ADD CONSTRAINT DOC_MERCANTIL_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_Cod_Cliente
    ) 
    REFERENCES CLIENTE 
    ( 
     Cod_Cliente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE HORAS_POR_FACTURAR 
    ADD CONSTRAINT HORAS_POR_FACTURAR_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_Cod_Cliente
    ) 
    REFERENCES CLIENTE 
    ( 
     Cod_Cliente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE HORAS_POR_FACTURAR 
    ADD CONSTRAINT HORAS_POR_FACTURAR_FACTURA_FK FOREIGN KEY 
    ( 
     FACTURA_No_Factura
    ) 
    REFERENCES FACTURA 
    ( 
     No_Factura 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE JUICIOS 
    ADD CONSTRAINT JUICIOS_ABOGADO_FK FOREIGN KEY 
    ( 
     ABOGADO_Cod_Abog
    ) 
    REFERENCES ABOGADO 
    ( 
     Cod_Abog 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE JUICIOS 
    ADD CONSTRAINT JUICIOS_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_Cod_Cliente
    ) 
    REFERENCES CLIENTE 
    ( 
     Cod_Cliente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PODERES 
    ADD CONSTRAINT PODERES_ABOGADO_FK FOREIGN KEY 
    ( 
     ABOGADO_Cod_Abog
    ) 
    REFERENCES ABOGADO 
    ( 
     Cod_Abog 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PODERES 
    ADD CONSTRAINT PODERES_CLIENTE_FK FOREIGN KEY 
    REFERENCES CLIENTE 
    ( 
     Cod_Cliente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RECURSOS 
    ADD CONSTRAINT RECURSOS_ABOGADO_FK FOREIGN KEY 
    ( 
     ABOGADO_Cod_Abog
    ) 
    REFERENCES ABOGADO 
    ( 
     Cod_Abog 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RECURSOS 
    ADD CONSTRAINT RECURSOS_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_Cod_Cliente
    ) 
    REFERENCES CLIENTE 
    ( 
     Cod_Cliente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             38
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   7
-- WARNINGS                                 0
